name: test-workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Commands
        run: |
          node -v
          npm -v
  parallel-jobs-macos:
    runs-on: macos-lates
    steps:
      - name: View SW Version
        run: sw_vers
  dependand-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Steps
        run: doesnotexist
